-- CreateEnum
CREATE TYPE "ExerciseType" AS ENUM ('STRENGTH', 'BODY_WEIGHT', 'STRETCHING', 'CARDIO', 'PLYOMETRIC', 'MOBILITY', 'BALANCE');

-- CreateEnum
CREATE TYPE "Equipment" AS ENUM ('BODYWEIGHT', 'DUMBBELL', 'BARBELL', 'EZ_BAR', 'TRAP_BAR', 'KETTLEBELL', 'MEDICINE_BALL', 'SLAM_BALL', 'WEIGHT_PLATE', 'RESISTANCE_BAND', 'CABLE', 'MACHINE', 'SMITH_MACHINE', 'LEG_PRESS', 'HACK_SQUAT_MACHINE', 'BENCH_FLAT', 'BENCH_INCLINE', 'BENCH_DECLINE', 'BENCH_ADJUSTABLE', 'SQUAT_RACK', 'POWER_RACK', 'PULL_UP_BAR', 'DIP_STATION', 'SUSPENSION_TRAINER', 'AB_WHEEL', 'STABILITY_BALL', 'BOSU_BALL', 'FOAM_ROLLER', 'YOGA_MAT', 'TREADMILL', 'STATIONARY_BIKE', 'ROWING_MACHINE', 'ELLIPTICAL', 'STAIRMASTER', 'JUMP_ROPE', 'BATTLE_ROPES', 'SLED', 'SANDBAG', 'LANDMINE', 'BOX', 'PARALLEL_BARS', 'OTHER');

-- CreateEnum
CREATE TYPE "TrackingField" AS ENUM ('REPETITIONS', 'TIME', 'DISTANCE', 'WEIGHT', 'RPE', 'HEART_RATE');

-- CreateEnum
CREATE TYPE "TargetArea" AS ENUM ('UPPER_BODY', 'LOWER_BODY', 'CORE', 'FULL_BODY');

-- AlterTable
ALTER TABLE "Exercise" ADD COLUMN     "equipmentTypes" "Equipment"[] DEFAULT ARRAY[]::"Equipment"[],
ADD COLUMN     "exerciseType" "ExerciseType",
ADD COLUMN     "targetAreas" "TargetArea"[] DEFAULT ARRAY[]::"TargetArea"[],
ADD COLUMN     "trackingFields" "TrackingField"[] DEFAULT ARRAY['REPETITIONS']::"TrackingField"[];
